### ISSUE TITLE
Fail to install ingition math

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-math#100]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/100)) by Guanghua Zha (Bitbucket: [sky99198](https://bitbucket.org/%7B027ea828-0635-4eb5-9afe-cd1a9e5f3879%7D/)).**

----------------------------------------
Follow this [https://ignitionrobotics.org/api/math/6.1/install.html](https://ignitionrobotics.org/api/math/6.1/install.html)

Got:    E: Unable to locate package libignition-math6-dev

‌

Tried to install ignition-math from source got:

Could not find a package configuration file provided by "ignition-cmake2"  
\(requested version 2.0.0\) with any of the following names:

```
ignition-cmake2Config.cmake
ignition-cmake2-config.cmake
```

‌

‌

Tried:   sudo apt-get install libignition-cmake2-dev

Got:   E: Unable to locate package libignition-cmake2-dev

‌

Installed Ignition CMake from source but did not resolve the problem above. 

‌

What should I do?

Thanks!

**Comment by luccosta** [comment]
I had the same problem and install the binary for the ignition-cmake2 to solve the dependency worked for me. I used:

`sudo apt install libignition-cmake2-dev`

This is something that worth it to put on README.md?

**Comment by chapulina** [comment]
@luccosta , what Ignition Math binary were you trying to install and in which platform? `ign-cmake2` should be installed automatically when you install `ign-math`, but there could be something broken for some specific platform.

**Comment by luccosta** [comment]
Used `ign-math6` and Ubuntu 18.04.

I was trying to install from source with the README guide [at the time](https://github.com/ignitionrobotics/ign-math/tree/45ff350f0a075c05fb78dfd615d6d3806181d3aa). I used the following commands:

```
sudo apt-get install libeigen3-dev

git clone https://github.com/ignitionrobotics/ign-math

cd ign-math; mkdir build; cd build; cmake ..; make
sudo make install
```

I see that the actual README dont offer an source installation, the recommended source installation is the complete installation of Ignition?

**Comment by chapulina** [comment]
> I see that the actual README dont offer an source installation

Good catch, the README is currently linking to https://ignitionrobotics.org/api/math/6.4/install.html, which doesn't have source install instructions. 

Pull request https://github.com/ignitionrobotics/ign-math/pull/147/ moved the source install instructions to the tutorial, but that targeted the `master` / `main` branch, which is not released yet, so the tutorials aren't live.

I'll backport that pull request to `ign-math6`.

**Comment by chapulina** [comment]
See https://github.com/ignitionrobotics/ign-math/pull/167

**Comment by addy1997** [comment]
I found a way to solve this 
 Go to the CMakeCache.txt file inside the build folder and change _browse the build directory_ to the path where 
```
 ignition-cmake2Config.cmake
ignition-cmake2-config.cmake
```
can be found. This worked for me.
