### ISSUE TITLE
[Window] Error when install ign-math on Window10

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-math#105]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/105)) by drtritm (Bitbucket: [drtritm](https://bitbucket.org/%7B5dbcd483-85f9-4717-a95b-1974f18f1759%7D/)).**

----------------------------------------
Hello everyone.I tried to install Gazebo on window10 following the tutorial on here [http://gazebosim.org/tutorials?tut=install\_on\_windows&cat=install](http://gazebosim.org/tutorials?tut=install_on_windows&cat=install)  
But when I tried to configure ign-math \( step 9\). It keeps saying the following error  
" Could not find a package configuration file provided by "ignition-cmake2" "  
I tried to clone ignition-cmake2 into folder "gz-ws" and configure it and succeeded. But ign-math still not worked.  
The same issue happen with ign-transport, it require ignition-cmake0. Could anyone help me.  
Thanks for reading

**Comment by lnoah995** [comment]
Has this issue been resolved or not? I can't seem to get it working. I get the following error , and am at a loss of what to do.

 By not providing "Findignition-cmake0.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-cmake0", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-cmake0"
  (requested version 0.3.0) with any of the following names:

    ignition-cmake0Config.cmake
    ignition-cmake0-config.cmake

**Comment by SafetyLok** [comment]
To overcome this issue I changed the configure.bat file for ign-math by adding:

`-Dignition-cmake0_DIR="G:\gz-ws\ign-cmake\build\install\Release\lib\cmake\ignition-cmake0"`

**Comment by azeey** [comment]
Not sure if this issue is still valid. Feel free to reopen if you're still having problems.
