### ISSUE TITLE
math::parseFloat is locale-dependent

### ISSUE THREAD

**Issue by darksylinc** [gazebosim/gz-math#215]
## Environment
* OS Version: Ubuntu 18.04 LTS
* Source or binary build? ign-math6 9519ce74dae8b8c68303ef81e85fda27d9f4f494
    
`parseFloat` relies on `std::stod` which is locale-dependent.

When using my locale LC_NUMERIC=es_AR.UTF-8; the Collada importer in ign-common/graphics/src/ColladaLoader.cc will end up reading garbage. Hence this little sensor:

![Collada](https://user-images.githubusercontent.com/3395130/126920598-7ca004a6-61b9-40ea-893b-efd1617eafeb.jpg)

will end up looking like this:

![BadMarv](https://user-images.githubusercontent.com/3395130/126874160-993bff4c-5fed-4836-ba8a-ce8f51afb226.png)

This bug is related to https://github.com/ignitionrobotics/ign-common/pull/120 and https://github.com/ignitionrobotics/ign-rendering/pull/365

## Description
* Expected behavior: Collada loads the importer correctly
* Actual behavior: Collada loads a triangle soup

## Steps to reproduce

1. Launch `LC_ALL=es_AR.UTF-8 ign gazebo near_clip.sdf` using [near_clip.sdf](https://gist.github.com/iche033/c4c679738ef348b905e9ec8ca19efbbe)

## Workaround

Launching gazebo with LC_ALL=C fixes the issue.

**Comment by j-rivero** [comment]
I'm centralizing the information and issues related to locale independent conversions in ignitionrobotics/ign-common#233. PRs are very welcome :)

**Comment by azeey** [comment]
Closing in favor of https://github.com/gazebosim/gz-common/issues/233.
