### ISSUE TITLE
Vector3 operator <

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-math#41]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/41)) by Denys Kotelovych (Bitbucket: [ilidar](https://bitbucket.org/%7Bd5d4aed9-44fc-4a54-9c61-5b97c922b704%7D/)).**

----------------------------------------
This commit caused undefined behavior or even assert for sorting Vector3
1a0288f6537dacdb05a3163423797055c4677486, e.g.:

v1 = (1.0, 2.0, 3.0), v2 = (3.0, 2.0, 1.0)

Probably would be better to use something like this:
```
#!c++
bool operator<(const Vector3d &lhs, const Vector3d &rhs) {
  if (lhs.X() < rhs.X())
    return true;
  if (lhs.X() > rhs.X())
    return false;
  return lhs.Y() < rhs.Y();
}
```

**Comment by chapulina** [comment]
This is the current operator on the `master` branch:

https://github.com/ignitionrobotics/ign-math/blob/fdbd226d70885e85e265d7c61cfa9014bee1a33a/include/ignition/math/Vector3.hh#L731-L735

**Comment by azeey** [comment]
The way this is implemented [currently](https://github.com/gazebosim/gz-math/blob/a527e1422c25df73e30ee4f0c38ccbe56f6da4e4/include/gz/math/Vector3.hh#L721) seems okay to me. Closing.
