### ISSUE TITLE
Stream operators have low precision

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-math#47]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/47)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
The stream operators in several classes currently have limited precision, presumably for decluttering console output. Several examples:

* [Vector3](https://github.com/ignitionrobotics/ign-math/blob/9f1c0ba1d40df7f450607162f9c4edb91f605818/include/ignition/math/Vector3.hh#L710)
* [Quaternion](https://github.com/ignitionrobotics/ign-math/blob/9f1c0ba1d40df7f450607162f9c4edb91f605818/include/ignition/math/Quaternion.hh#L995)

This is a warning not to use them for lexical casting, as they will lose significant precision.

**Comment by azeey** [comment]
I think this has been fixed by https://github.com/gazebosim/gz-math/pull/376 where the precision can be set using `std::setprecision`.
