### ISSUE TITLE
Point GitHub About link to https://gazebosim.org/libs/math

### ISSUE THREAD

**Issue by traversaro** [gazebosim/gz-math#517]
## Desired behavior

Navigating the GitHub repo with @giotherobot, I clicked on the about link that pointed us to the generic Gazebo website. Could it make more sense to point it to https://gazebosim.org/libs/math that seems more relevant to the library?

## Alternatives considered

Keep the current link to  https://gazebosim.org .

## Implementation suggestion

Change the GitHub About link to https://gazebosim.org/libs/math .

## Additional context

N/A

**Comment by azeey** [comment]
Pointing the the library page makes sense to me.

**Comment by scpeters** [comment]
I just made the change; thanks!
