### ISSUE TITLE
Pose addition and subtraction needs work [gazebo issue 216]

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-math#60]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/60)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Moving Gazebo issue 216 here now that gazebo::math has been fully deprecated. Please consider the discussion on that issue:

https://bitbucket.org/osrf/gazebo/issues/216/pose-addition-and-subtraction-needs-work

**Comment by traversaro** [comment]
I think this has been fixed (unfortunately with breaking change in the behavior of `operator*(Pose3d, Pose3d)` in ignition-math6 with PR https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/301 right? See https://github.com/ignitionrobotics/ign-math/blob/master/Changelog.md#ignition-math-620 .

**Comment by chapulina** [comment]
I think there's still the question of whether we want to remove the addition and subtraction operators:

https://github.com/ignitionrobotics/ign-math/blob/6a3c4a32b18e6bd7956fecfe53ccfe14bfcd2907/include/ignition/math/Pose3.hh#L183-L189

**Comment by scpeters** [comment]
yeah, I would support deprecating them to encourage the use of `*`

**Comment by traversaro** [comment]
> yeah, I would support deprecating them to encourage the use of `*`

I personally agree. `+` is often used to refer to commutative operations, and using it for a non-commutative operation is quite confusing.

**Comment by scpeters** [comment]
I'll open a pull request to deprecate the `+` and `-` operators for ign-math7 and see how much trouble it causes

**Comment by scpeters** [comment]
Pose `+` and `-` operators are now deprecated in `math7`
