### ISSUE TITLE
Stray tag 'rm'

### ISSUE THREAD

**Issue by jwnimmer-tri** [gazebosim/gz-math#654]
## Description

It seems like `gz-math` has a mistaken tag pushed, named `rm`:
* https://github.com/gazebosim/gz-math/releases/tag/rm

I imagine that is unwanted, so I thought I'd mention it here in case you wanted to delete it.

---

Also BTW it's impossible for me to tell for sure, but it seems like the `gz-math8_8.1.0` tag was initially pushed to point to 74416aa but then later was overwritten with 2179284c?

If that's what happened, then please note that overwriting release tags is **extremely bad juju** and causes all kinds of headaches for downstream projects.  Luckily Drake mirrors all of our externals so the change to source code integrity only generated a warning instead of a build error, but other projects might not be so lucky.  If mistake happens during the release process that's understandable, but in that case please consider doing another patch release right away (e.g., 8.1.1), instead of overwriting an existing one.

Or if that's not what happened and instead it was some mistake in Drake's mirroring, I'm sorry and please excuse the interruption.

**Comment by azeey** [comment]
Yeah, I think the `rm` tag was a mistake. I'll remove it shortly.

> Also BTW it's impossible for me to tell for sure, but it seems like the gz-math8_8.1.0 tag was initially pushed to point to https://github.com/gazebosim/gz-math/commit/74416aa427b5e88dab6ef69cbaedeaa4a1e1a57e but then later was overwritten with https://github.com/gazebosim/gz-math/commit/2179284cb6fe77f42001c4797e060c034d8e92dc?

You are correct. There was an error in the initial release and the 8.1.0 tag was attached to the wrong commit. I overwrote the tag when fixing the release thinking overwriting was better than having the tag point to the wrong commit. In hindsight, it was the wrong thing to do. My apologies for the headache.
